version: '3.8'
services:
  landlord-db:
    container_name: landlord-db
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: landlord-nest
      PGDATA: /var/lib/postgresql/data
    networks:
      landlordnet:
        ipv4_address: 192.168.1.100
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
  landlord-storage:
    container_name: landlord-storage
    image: minio/minio:latest
    ports:
      - 9010:9000
      - 9011:9090
    environment:
      MINIO_ROOT_USER: minioaadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    networks:
      landlordnet:
        ipv4_address: 192.168.1.101
    volumes:
      - 'minio:/data/minio'
    restart: unless-stopped
    command: minio server /data/minio --console-address ":9090"
  # landlord-dev:
  #   build: .
  #   ports:
  #     - '3030:3030'
  #   environment:
  #     NODE_ENV: development
  #   networks:
  #     landlordnet:
  #       ipv4_address: 192.168.1.102
networks:
  landlordnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
volumes:
  postgres:
  minio:
