version: '3.8'
services:
  landlord-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: landlord-nest
    networks:
      - madnessnet
    volumes:
      - 'postgres:/data/postgres'
networks:
  madnessnet:
volumes:
  postgres:
