version: '3.8'
services:
  landlord-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: landlord-nest
    networks:
      landlordnet:
    volumes:
      - 'postgres:/data/postgres'
  landlord-minio:
    image: minio/minio:latest
    ports:
      - 9010:9000
      - 9011:9090
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    networks:
      landlordnet:
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
networks:
  landlordnet:
volumes:
  postgres:
  minio:
